version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    networks:
      - evolution-net
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379
    expose:
      - 6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres_data:
  evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
